### ISSUE TITLE
plexDIA in DIA-NN

### ISSUE THREAD

**Issue by Dmorgen** [SlavovLab/plexDIA#1]
Hi, 

I'm a little unclear about the actual processing of plexDIA data. Is it fully incorporated in DIA-NN or do you have to run your script after DIA-NN analysis? if so, on what files and what settings in DIA-NN?

Thanks!
David.

**Comment by j-derks** [comment]
Hi David!

Below is a link to a tutorial we just made that will hopefully be helpful for reproducing the plexDIA searches in DIA-NN. The data analysis that is shown in the paper is from results produced by DIA-NN, we then took those results from the main .tsv output and did our own data analysis with the R script "FigureGen_10262021.Rmd". 

https://www.youtube.com/watch?v=0Wmg9LjDtgE&ab_channel=NikolaiSlavov

Please reach out again if something is still unclear!
Best regards,
Jason

**Comment by Dmorgen** [comment]
Awesome, thanks!

D.
