### ISSUE TITLE
plexDIA for TMT labelled sample

### ISSUE THREAD

**Issue by sughforge** [SlavovLab/plexDIA#2]
Hi,
Just wondering if plexDIA can be used for TMT labeled samples!

Thanks,
Sudip

**Comment by nslavov** [comment]
plexDIA can work with different types of non-isobaric mass tags. Current commercially available labels for plexDIA include mTRAQ, TMT0/TMT/shTMT, and dimethyl labeling. You can read more about these options in the discussion section of [Derks et al., 2021](https://www.biorxiv.org/content/10.1101/2021.11.03.467007v2.full), doi: [10.1101/2021.11.03.467007](https://doi.org/10.1101/2021.11.03.467007)

**Comment by sughforge** [comment]
Thanks Nikolai!
