### ISSUE TITLE
mTRAQ_DDA_PGs file

### ISSUE THREAD

**Issue by jonathanly3210** [SlavovLab/plexDIA#3]
Hi, as I was trying to replicate the data analysis with your code it appears I cannot find the report file labelled mTRAQ_DDA_PGs in the MassIVE MSV000089093 Files database. 

Thanks
-Jonathan

**Comment by j-derks** [comment]
Hi Jonathan, sorry about that! It looks like I didn't rename that file before uploading. It's currently there (MassIVE MSV000089093), just named "proteinGroups.txt". So you can use that; alternatively, I'm re-uploading the same file with the correct name now - should hopefully be available in a few minutes. 

Best,
Jason

**Comment by jonathanly3210** [comment]
Hi Jason, thanks for the quick response. I figured that was the issue and tried it last night by redirecting the variable to the proteinGroups.txt file last night. For some reason I got an error last night but I tried it again this morning and it seems to be running fine. Ill retry the whole thing with the new file once its uploaded.

-Jonathan

**Comment by j-derks** [comment]
OK, reach out if it's still a problem or you run into other issues!
