### ISSUE TITLE
Cannot distinguish information from each channel for plexDIA 

### ISSUE THREAD

**Issue by ningzaizai** [SlavovLab/plexDIA#5]
Dear Pro. f Slavov:
My name is Ningzaizia and from China.
Now I have a question for plexDIA by using your paper data (MassIVE MSV000088302 Files) to test the plexDIA workflow in my Lab.  I load your pipeline (Report.auto.pipeline) and raw data (eJD905.raw,eJD906.raw,eJD907.raw) into the DIANN(1.8.1) and run successfully. 
However, my results just contain 14 files, please read the screenshot (diaNN-result), and It does not contain channels-relative files. Importantly, I cannot tell which protein comes from which channel, please read the screenshot (diaNN-result2).
These parameters I set in the DIA-NN is coincident with the Report.auto.pipeline, apart from modifying the path of raw data, fasta file and output. 
I’m not sure where I went wrong. Can you help me troubleshoot?

![diaNN-result](https://github.com/SlavovLab/plexDIA/assets/81786796/edb88484-354f-45cc-aaa7-9a1aa29229af)

![diaNN-result2](https://github.com/SlavovLab/plexDIA/assets/81786796/b68d3e88-e09b-4a89-8c09-49894d8121b2)

![diaNN-parameters](https://github.com/SlavovLab/plexDIA/assets/81786796/c88e5980-762a-4153-afe0-66909fb97203)

**Comment by j-derks** [comment]
Hi Ningzaizia,

Thanks for testing the plexDIA workflow and for detailing the issue you're having. The plexDIA pipeline found in the MSV000088302 repository works for older versions of DIANN but is incompatible with DIANN v1.8.1. Please see the repository (MSV000089093) that was published with the plexDIA paper, which contains a pipeline that works with DIANN v1.8.1. Alternatively, here is a direct link to the correct pipeline.
https://drive.google.com/file/d/1YqMQ7v9Ps_CjuRemBH5UN_eXeebPAPy9/view?usp=drive_link

There were some changes to the commands. One in particular, requiring to specify "nK" for each of the channels in the channels command. (--channels mTRAQ, 0, nK, 0:0; mTRAQ, 4, nK, 4.0070994:4.0070994; mTRAQ, 8, nK, 8.0141988132:8.0141988132)

Please try again with the pipeline I linked; this is the one we used in the paper. 

Feel free to reach out if you run into any other issues! Thanks!
Jason

**Comment by ningzaizai** [comment]
Hi Jason，
Thanks for your response very much. I have run the plexDIA workflow successfully by using the new pipeline. 
I have another question:  Is the protein abundance based on MS1 intensity or MS2 intensity? 

![searchpipeline](https://github.com/SlavovLab/plexDIA/assets/81786796/254af7f9-7334-4609-af0c-7d3fbf7879c2)

**Comment by j-derks** [comment]
Glad it worked! The precursor-level information is now channel specific, however the protein abundances are not channel specific. To get channel specific protein-level quantities, I use the DIANN r package to convert either the Ms1.Area (MS1 quant) or Precursor.Translated (MS2 quant) columns to MaxLFQ protein quantities for each channel. https://rdrr.io/github/vdemichev/diann-rpackage/man/diann_maxlfq.html

The only modifications you'll need to do is 1) **make the File.Name channel specific** so the maxLFQ function can output quantities for each protein respective to each channel and file, and 2) **Remove the channel specifiers from Precursor.Id**. The output will be a matrix of maxLFQ protein quantities for each channel and file.

**Comment by ningzaizai** [comment]
Thanks for your response details very much.  Now I understand it.
I am sorry to tell you that I ran into another issue.  I want to analyze  DIA raw data with dimethyl label using the plexDIA workflow, however, the library cannot generate successfully based on the fasta file by Dimethyl replace mTRAQ, please read the screenshot (libraryParameter).  The warning is listed below (log).

What can I modify parameters if I want to analyze the dimethyl label DIA data? Can you help me? Thanks a lot!

Best
Ningzaizai
![libraryParameter](https://github.com/SlavovLab/plexDIA/assets/81786796/0cfb9447-1731-483a-b955-c51eddd062bd)

![log](https://github.com/SlavovLab/plexDIA/assets/81786796/e34a952b-f8a3-4e91-9ab3-2f141f3a78d4)

**Comment by j-derks** [comment]
The commands you're using seem correct, but it seems like DIA-NN is unable to predict dimethyl iRTs and spectra; Vadim Demichev would be a better person to ask about this. In the meantime for dimethyl labeling, I would suggest using the libraries generated by Thielert et al which can be found here: https://www.ebi.ac.uk/pride/archive/projects/PXD038632

**Comment by ningzaizai** [comment]
Hi Jason,
Thanks for your response very much. Now my issue is dealt with well.  

Best
Ningzaizai
