### ISSUE TITLE
Quantification strategy

### ISSUE THREAD

**Issue by weixiandeng** [SlavovLab/plexDIA#6]
Hi Drs. Derks and Slavov,

In your tutorial, I noticed that 'peak height' was advised to set in quantification strategy field. I'm wondering is there any particular reason for choosing it, how it would impact the data? 

Best,
Weixian

**Comment by j-derks** [comment]
Hi Weixian,

Quantitative accuracy seems best when we use peak height as opposed to the extracted signal from many scans. Peak height extracts signal from the apex and immediately adjacent scans, which reduces the impact of interferences. If one does not use peak height, the accuracy of quantitation would likely decrease slightly. How much it decreases would likely depend on frequency of sampling and how many scans are used for quantitation.

Best,
Jason

**Comment by weixiandeng** [comment]
Thanks for you prompt response! it makes a lot sense.
